{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "demo-hello-world.serviceAccountName" . }}
  labels:
{{ include "demo-hello-world.labels" . | indent 4 }}
{{- end -}}
