name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: goto app folder
      run: cd hello-world-web-app
    - name: init
      run: appVersion=$(cat package.json | jq '.version')
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: priyakant/repository/image
        username: priyakant
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: docker.pkg.github.com
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world-web-app:$appVersion
    - name: Tag latest
      run: docker tag priyakant/hello-world-web-app:$appVersion priyakant/hello-world-web-app:latest
    - name: Docker push-latest
      run: docker push priyakant/hello-world-web-app:latest
    - name: Docker push-ver
      run: docker push priyakant/hello-world-web-app:$appVersion
