name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: init
      run: appVersion=$(cat ./hello-world-web-app/package.json | jq '.version')
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: $DOCKER_HUB_USERNAME/repository
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file ./hello-world-web-app/Dockerfile --tag hello-world-web-app:$appVersion
    - name: Tag latest
      run: docker tag $DOCKER_HUB_USERNAME/hello-world-web-app:$appVersion $DOCKER_HUB_USERNAME/hello-world-web-app:latest
    - name: Docker push-latest
      run: docker push $DOCKER_HUB_USERNAME/hello-world-web-app:latest
    - name: Docker push-ver
      run: docker push $DOCKER_HUB_USERNAME/hello-world-web-app:$appVersion
