name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: priyakant/hello-world-web-app-x
        registry: docker.io
        dockerfile: hello-world-web-app/Dockerfile
        username: priyakant
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
