name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: init
      run: export appVersion=$(cat ./hello-world-web-app/package.json | jq '.version')
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: priyakant/hello-world-web-app-x:${{ appVersion }}
        username: priyakant
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        workdir: hello-world-web-app

